apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerdemo
  labels:
    app: dockerdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockerdemo
  template:
    metadata:
      labels:
        app: dockerdemo
    spec:
      containers:
      - name: dockerdemo
        image: vasuklk/vasudocker
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dockerdemo
spec:
  selector:
    app: dockerdemo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer