name: Docker Image CI

on:
  push:
    branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags: 
        description: 'Test scenario'

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push to Dockerhub
        working-directory: VasuDocker/VasuDocker
        run: |
          docker build -f VasuDocker/Dockerfile .
#         uses: docker/build-push-action@v3
#         with:
#           context: .
#           file: ./VasuDocker/VasuDocker/Dockerfile
#           push: true
#           tags: vasuklk/vasudocker:1.1
